#!/bin/bash
echo " Hello, give me the permission to install wireguard (yes/no)"
read permission
if [ "$permission" = "no" ]
then
        echo " you choose no , we are not installing wireguard for you"
else [ "$permission" = "yes" ]
        echo "processing start"

apt update
apt install wireguard -y
wg genkey | sudo tee /etc/wireguard/private.key
chmod go= /etc/wireguard/private.key
cat /etc/wireguard/private.key | wg pubkey | sudo tee /etc/wireguard/public.key
touch /etc/wireguard/wg0.conf
ufw allow 51820/udp
ufw allow OpenSSH
ufw allow 22/tcp
ufw disable
ufw enable
ufw status
systemctl enable wg-quick@wg0.service
systemctl start wg-quick@wg0.service
systemctl status wg-quick@wg0.service
echo "******************************************************************* Thanks for installing Wireguard **************************************************************************"
echo "*********************************************************************** Enjoy Wireguard services *****************************************************************************"

fi

